<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/Applications_of_Linear_Systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import solve

A = np.array([[4,5],[3,-2]])
print(A)
B = np.array ([[7],[11]])
print(B)

inv_A = np.linalg.inv(A)
print(inv_A)

X = np.linalg.inv(A).dot(B)
print(X)



[[ 4  5]
 [ 3 -2]]
[[ 7]
 [11]]
[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]
[[ 3.]
 [-1.]]


In [2]:
inv_A = np.linalg.inv(A)
print(inv_A)

X = np.dot(inv_A,B)
print(X)

[[ 0.08695652  0.2173913 ]
 [ 0.13043478 -0.17391304]]
[[ 3.]
 [-1.]]


In [3]:
X = np.linalg.solve(A,B)
print(X)

[[ 3.]
 [-1.]]
