<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/BAQUIRAN_PrelimExam_LinearAlgebra_58020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LINEAR ALGEBRA PRELIM EXAM**

Question 1

In [ ]:
import numpy as np

a = np.array([1,1,1,1])

diagonal = np.diag(a)

print(diagonal)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 2

In [ ]:
a = np.array([1,1,1,1])

a *= 1
diagonal = np.diag(a)

print(diagonal)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Question 3

In [2]:
import numpy as np

a = np.array([2,7,4])
b = np.array ([3,9,8])

c = np.cross(a,b)

print(c)

[20 -4 -3]
