<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/BAQUIRAN_MidtermsActivity1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

#main array
a = np.array([[-5,0,6], 
              [4,1,2], 
              [4,9,8]])

#inverses values
b = np.linalg.inv(a)

print("Original Array")
print(a)

#transposed elements of array A
print("transposed elements of array A")
print(np.transpose(a))

#transposed elements with inverse value
print("transposed elements of array A that have inverse value")
print(np.transpose(b))

Original Array
[[-5  0  6]
 [ 4  1  2]
 [ 4  9  8]]
transposed elements of array A
[[-5  4  4]
 [ 0  1  9]
 [ 6  2  8]]
transposed elements of array A that have inverse value
[[-0.04132231 -0.09917355  0.1322314 ]
 [ 0.2231405  -0.26446281  0.18595041]
 [-0.02479339  0.14049587 -0.02066116]]
