<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/BaquiranCharlesJustinPythonExercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

             

In [8]:
#Sum
a = np.array([[-5,0], [4,1]])
b = np.array([[6,-3], [2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [9]:
#Difference1
a = np.array([[-5,0], [4,1]])
b = np.array([[6,-3], [2,3]])
print(a-b)

[[-11   3]
 [  2  -2]]


In [10]:
#Difference2
a = np.array([[-5,0], [4,1]])
b = np.array([[6,-3], [2,3]])
print(b-b)

[[0 0]
 [0 0]]
