<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
#Problem 2. 
import numpy as np
a = np.array([[3, 1, 1], [9, -3, 3], [-12, 4, -4]])
b = np.array([5, 15, -20])
x = np.linalg.solve(a, b)
print (x)

#An error occurs because the matrix has no solution


LinAlgError: ignored

In [4]:
#Problem 3

import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

#Calculates the eigen values and eigen vectors W for eigenvalues V for eigenvectors
w,v = np.linalg.eig(A)
print("The eigenvalues is/are", w)
print("The right eigenvectors are", v)

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalues is/are [-1.  3.  2.]
The right eigenvectors are [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
