<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/MidtermExamBaquiran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
#Question 1. Create a Python code that displays a square matrix whose length is 5
print("Question 1")

a = np.array ([[5,5,5,5,5],[6,6,6,6,6],[7,7,7,7,7],[8,8,8,8,8],[9,9,9,9,9],[1,1,1,1,1]])
print(a)

Question 1
[[5 5 5 5 5]
 [6 6 6 6 6]
 [7 7 7 7 7]
 [8 8 8 8 8]
 [9 9 9 9 9]
 [1 1 1 1 1]]


In [31]:
import numpy as np
#Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero
print("Question 2")

a = np.array ([[6,5,7],[0,3,9],[0,0,2]])
print(a)

Question 2
[[6 5 7]
 [0 3 9]
 [0 0 2]]


In [24]:
import numpy as np

#Question 3. Create a Python code that displays a square matrix which is symmetrical
print("Question 3")


#Prints Original Matrix
A = np.array([[6,1,6],[1,5,2],[6,2,7]])
print(A)
print("\n")

#prints transposed matrix
print(np.transpose(A))



Question 3
[[6 1 6]
 [1 5 2]
 [6 2 7]]


[[6 1 6]
 [1 5 2]
 [6 2 7]]


In [25]:
import numpy as np
#Question 4. What is the inverse of matrix C? Show your solution by python coding.
print(" Question 4")

C = np.array([[1,2,3],[2,3,3],[3,4,-2]])

#Inverses Values
inverseC=np.linalg.inv(C)

#Prints inversed values
print(inverseC)

n Question 4
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [29]:
#Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding
print("Question 5")

import numpy as np

#Displays Matrix
a = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
print(a)

#Calculates and rounds off the value of the determinant
print(round(np.linalg.det(a)))

Question 5
[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5


In [33]:
import numpy as np
#Question 6. Find the roots of the linear equations by showing its python codes

print("Question 6")
#Displays matrix
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
print (A)
print("\n")
#Inverses value of matrix
inverseA=np.linalg.inv(A)

B = np.array ([[3.4,],[8.8],[19.2]])
print(B)
print("\n")

#Calculates the roots of the given linear equation
roots = np.dot(inverseA,B)
print(roots)

Question 6
[[ 5  4  1]
 [10  9  4]
 [10 13 15]]


[[ 3.4]
 [ 8.8]
 [19.2]]


[[0.2]
 [0.4]
 [0.8]]
