<a href="https://colab.research.google.com/github/BaquiranCharlesJustin/Linear-Algebra---58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical Lab Exam 1

In [2]:
import numpy as np

Problem 1

In [26]:
# a. WY

A = np.array([[1,-3],[2,-2],[3,1]])
B = np.array([[1,2,0],[0,-1,2]])

print(np.dot(A,B))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [14]:
#b. Z+Z

a = np.array([[0,1],[2,3]])

print(a+a)

[[0 2]
 [4 6]]


In [51]:
#c. 3X

A = np.array([[3,2,1],[-1,2,3],[2,-1,1]])

print(A*3)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2


In [50]:
#Problem2A

A = np.array([[1,-3],[2,-2],[3,1]])
B = np.array([[1,2,0],[0,-1,2]])

D = np.dot(B,A)

print(D*D)

#Statement is not true

[[25 49]
 [16 16]]


Result for 

In [45]:
#Problem2B
A = np.array([[1,-3],[2,-2],[3,1]])
B = np.array([[1,2,0],[0,-1,2]])
C= np.array([[3,2,1],[-1,2,3],[2,-1,1]])

D = np.dot(A,B)

print(np.subtract(D,C))

#Statement is true


[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [49]:
#Problem2C
A = np.array([[1,-3],[2,-2],[3,1]])
B = np.array([[1,2,0],[0,-1,2]])
C= np.array([[0,1],[2,3]])

D = np.dot(B,A)
E = C*C

#Statement is not true

print(np.subtract(D,E))

[[ 5 -8]
 [ 0 -5]]
